type AnalyticsEnv = { DB: D1Database; ANALYTICS_VIEW_TOKEN?: string }

const EVENT_LABELS: Record<string, string> = {
  landing_view: '랜딩 방문', app_view: '정식 서비스 방문', demo_view: '데모 방문', landing_app_click: '서비스 시작 클릭',
  room_created: '여행방 생성', recommendations_viewed: '추천 확인', final_route_confirmed: '최종 경로 확정',
  schedule_edit: '일정 편집', schedule_copy: '일정 복사', feedback_helpful: '도움 됨', feedback_not_helpful: '아쉬움',
  demo_room_created: '데모 여행방 생성', demo_recommendations_viewed: '데모 추천 확인', demo_final_route_confirmed: '데모 최종 경로',
}

const csvCell = (value: unknown) => `"${String(value ?? '').replace(/"/g, '""')}"`

export async function handleAnalyticsDashboard(request: Request, env: AnalyticsEnv, url: URL) {
  if (!url.pathname.startsWith('/insights/')) return null
  const token = decodeURIComponent(url.pathname.slice('/insights/'.length)).replace(/\/$/, '')
  if (!env.ANALYTICS_VIEW_TOKEN || token !== env.ANALYTICS_VIEW_TOKEN) return new Response('Not Found', { status: 404 })
  if (request.method !== 'GET') return new Response('Method Not Allowed', { status: 405 })

  const period = ['7', '30', '90', 'all'].includes(url.searchParams.get('period') ?? '') ? url.searchParams.get('period')! : '30'
  const cutoff = period === 'all' ? '2000-01-01' : `-${Number(period) - 1} days`
  const eventDateCondition = period === 'all' ? 'event_date>=?1' : "event_date>=date('now','+9 hours',?1)"
  const feedbackDateCondition = period === 'all' ? 'feedback_date>=?1' : "feedback_date>=date('now','+9 hours',?1)"

  if (url.searchParams.get('format') === 'json' || url.searchParams.get('format') === 'csv') {
    const [totals, daily, campaigns, feedbackSummary, feedbackReasons, feedbackPlatforms, recentFeedback] = await Promise.all([
      env.DB.prepare(`SELECT event_name,SUM(event_count) event_count,SUM(session_count) session_count FROM anonymous_event_counts WHERE ${eventDateCondition} GROUP BY event_name ORDER BY session_count DESC`).bind(cutoff).all(),
      env.DB.prepare(`SELECT event_date,event_name,SUM(event_count) event_count,SUM(session_count) session_count FROM anonymous_event_counts WHERE ${eventDateCondition} GROUP BY event_date,event_name ORDER BY event_date`).bind(cutoff).all(),
      env.DB.prepare(`SELECT campaign_source,campaign_medium,campaign_name,event_name,SUM(event_count) event_count,SUM(session_count) session_count FROM anonymous_event_counts WHERE ${eventDateCondition} AND (campaign_source<>'' OR campaign_medium<>'' OR campaign_name<>'') GROUP BY campaign_source,campaign_medium,campaign_name,event_name ORDER BY session_count DESC LIMIT 300`).bind(cutoff).all(),
      env.DB.prepare(`SELECT sentiment,COUNT(*) count FROM anonymous_feedback WHERE ${feedbackDateCondition} GROUP BY sentiment`).bind(cutoff).all(),
      env.DB.prepare(`SELECT reason,COUNT(*) count FROM anonymous_feedback WHERE ${feedbackDateCondition} AND reason<>'' GROUP BY reason ORDER BY count DESC`).bind(cutoff).all(),
      env.DB.prepare(`SELECT client_kind,COUNT(*) count FROM anonymous_feedback WHERE ${feedbackDateCondition} GROUP BY client_kind ORDER BY count DESC`).bind(cutoff).all(),
      env.DB.prepare(`SELECT feedback_date,sentiment,reason,comment,surface,client_kind FROM anonymous_feedback WHERE ${feedbackDateCondition} ORDER BY created_at DESC LIMIT 50`).bind(cutoff).all(),
    ])
    if (url.searchParams.get('format') === 'csv') {
      const rows = [['날짜', '이벤트', '이벤트 횟수', '익명 세션 수'], ...daily.results.map((row: any) => [row.event_date, EVENT_LABELS[row.event_name] ?? row.event_name, row.event_count, row.session_count])]
      return new Response('\uFEFF' + rows.map((row) => row.map(csvCell).join(',')).join('\r\n'), { headers: {
        'Content-Type': 'text/csv; charset=utf-8', 'Content-Disposition': `attachment; filename="mohang-insights-${period}days.csv"`,
        'Cache-Control': 'no-store', 'X-Robots-Tag': 'noindex, nofollow',
      } })
    }
    return Response.json({ labels: EVENT_LABELS, totals: totals.results, daily: daily.results, campaigns: campaigns.results, feedback: {
      summary: feedbackSummary.results, reasons: feedbackReasons.results, platforms: feedbackPlatforms.results, recent: recentFeedback.results,
    } }, { headers: { 'Cache-Control': 'no-store', 'X-Robots-Tag': 'noindex, nofollow' } })
  }

  return new Response(DASHBOARD_HTML, { headers: {
    'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'X-Robots-Tag': 'noindex, nofollow',
    'Referrer-Policy': 'no-referrer', 'Content-Security-Policy': "default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; frame-ancestors 'none'",
  } })
}

const DASHBOARD_HTML = `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex,nofollow"><title>모행 · 익명 통계</title><style>
:root{font-family:Pretendard,"Malgun Gothic",sans-serif;color:#191f28;background:#f7f8fa}*{box-sizing:border-box}body{margin:0}button,select{font:inherit}main{width:min(100% - 32px,980px);margin:auto;padding:38px 0 70px}header{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:20px}h1{margin:5px 0;font-size:30px;letter-spacing:-1.4px}header p,.muted{margin:0;color:#6b7684;font-size:13px}.badge{color:#1769cf;font-size:12px;font-weight:800}.toolbar{display:flex;gap:8px;margin-bottom:18px}.toolbar select,.toolbar a{min-height:40px;border:1px solid #d9dde3;border-radius:10px;background:#fff;padding:0 12px;color:#333;text-decoration:none;font-size:12px}.toolbar a{display:flex;align-items:center;font-weight:800}.cards,.feedback-overview{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.card,section{border:1px solid #e2e5e9;border-radius:16px;background:#fff}.card,.feedback-overview div{padding:18px}.card small,.feedback-overview small,.feedback-item small{color:#6b7684}.card b,.feedback-overview b{display:block;margin-top:8px;font-size:27px}.card em{display:block;margin-top:5px;color:#1769cf;font-size:11px;font-style:normal}section{margin-top:16px;padding:22px}h2{margin:0 0 5px;font-size:18px}.funnel,.daily,.campaigns,.feedback-list,.feedback-bars{display:grid;gap:10px;margin-top:18px}.row,.feedback-bar{display:grid;grid-template-columns:115px 1fr 52px;align-items:center;gap:10px;font-size:12px}.track{height:12px;overflow:hidden;border-radius:10px;background:#eef0f2}.fill{height:100%;border-radius:10px;background:#3182f6}.row strong,.feedback-bar strong{text-align:right}.daily-row{display:grid;grid-template-columns:76px 1fr 1fr;gap:8px;align-items:center;font-size:11px}.daily-row div{display:flex;height:22px;overflow:hidden;border-radius:6px;background:#eef0f2}.daily-row i{display:block;background:#3182f6}.daily-row i.demo{background:#8ebfff}.campaign,.feedback-item{padding:13px;border-radius:12px;background:#f7f8fa}.campaign{display:grid;grid-template-columns:1fr auto;gap:6px}.campaign b{font-size:13px}.campaign span,.empty{color:#6b7684;font-size:11px}.feedback-overview{grid-template-columns:repeat(3,1fr);margin-top:16px}.feedback-overview div{border-radius:12px;background:#f7f8fa}.feedback-list{max-height:430px;overflow:auto}.feedback-item{display:grid;gap:6px}.feedback-item p{margin:0;font-size:12px;line-height:1.55;white-space:pre-wrap}.loading{padding:80px 0;text-align:center;color:#6b7684}.error{color:#b42318}.privacy{margin-top:18px;color:#6b7684;font-size:11px;line-height:1.6}@media(max-width:680px){main{padding-top:24px}header{display:block}.toolbar{margin-top:15px}.cards{grid-template-columns:1fr 1fr}.feedback-overview{grid-template-columns:1fr}.card b{font-size:23px}.row,.feedback-bar{grid-template-columns:88px 1fr 40px}section{padding:17px}.campaign{grid-template-columns:1fr}.daily-row{grid-template-columns:68px 1fr}}
</style></head><body><main><header><div><span class="badge">MOHANG INSIGHTS</span><h1>익명 서비스 통계</h1><p>한국시간 기준 · 이름, 연락처, IP는 수집하지 않습니다.</p></div><p id="updated"></p></header><div class="toolbar"><select id="period" aria-label="조회 기간"><option value="7">최근 7일</option><option value="30" selected>최근 30일</option><option value="90">최근 90일</option><option value="all">전체</option></select><a id="csv" href="#">CSV 내려받기</a></div><div id="app" class="loading">통계를 불러오는 중이에요…</div></main><script>
const number=v=>new Intl.NumberFormat('ko-KR').format(v||0),esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={helpful:'도움 됨',not_helpful:'아쉬움',taste:'취향',route:'동선·이동',places:'장소',distance:'거리',wrong_place:'잘못된 장소 정보',other:'기타',android_app:'Android 앱',web_android:'Android 웹',web_ios:'iPhone 웹',web_desktop:'PC 웹',web:'웹'};
const sel=document.querySelector('#period'),params=new URLSearchParams(location.search);sel.value=params.get('period')||'30';sel.onchange=()=>{params.set('period',sel.value);location.search=params};document.querySelector('#csv').onclick=e=>{e.currentTarget.href=location.pathname+'?format=csv&period='+sel.value};
fetch(location.pathname+'?format=json&period='+sel.value,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{
 const counts=Object.fromEntries(data.totals.map(x=>[x.event_name,Number(x.session_count)])),views=counts.landing_view||0,apps=counts.app_view||0,demos=counts.demo_view||0,rooms=counts.room_created||0,finals=counts.final_route_confirmed||0,rate=(a,b)=>b?Math.round(a/b*1000)/10:0;
 const funnel=['landing_view','app_view','room_created','recommendations_viewed','final_route_confirmed'],max=Math.max(1,...funnel.map(k=>counts[k]||0)),grouped={},days={};
 data.campaigns.forEach(x=>{const key=[x.campaign_source||'(직접)',x.campaign_medium,x.campaign_name].filter(Boolean).join(' · ');grouped[key]=grouped[key]||{};grouped[key][x.event_name]=Number(x.session_count)});data.daily.forEach(x=>{days[x.event_date]=days[x.event_date]||{};days[x.event_date][x.event_name]=Number(x.session_count)});
 const dayMax=Math.max(1,...Object.values(days).flatMap(x=>[x.app_view||0,x.demo_view||0])),fb=data.feedback||{summary:[],reasons:[],platforms:[],recent:[]},summary=Object.fromEntries(fb.summary.map(x=>[x.sentiment,Number(x.count)])),helpful=summary.helpful||0,notHelpful=summary.not_helpful||0,totalFeedback=helpful+notHelpful,reasonMax=Math.max(1,...fb.reasons.map(x=>Number(x.count))),platformMax=Math.max(1,...fb.platforms.map(x=>Number(x.count)));
 const feedbackSection='<section><h2>사용자 피드백</h2><p class="muted">최종 경로 화면에서 제출한 익명 의견입니다.</p><div class="feedback-overview"><div><small>전체 응답</small><b>'+number(totalFeedback)+'</b></div><div><small>도움 됨</small><b>'+number(helpful)+'</b></div><div><small>만족도</small><b>'+rate(helpful,totalFeedback)+'%</b></div></div><h3>응답 사유</h3><div class="feedback-bars">'+(fb.reasons.map(x=>'<div class="feedback-bar"><span>'+esc(labels[x.reason]||x.reason)+'</span><div class="track"><div class="fill" style="width:'+Number(x.count)/reasonMax*100+'%"></div></div><strong>'+number(x.count)+'</strong></div>').join('')||'<div class="empty">아직 선택된 피드백 사유가 없습니다.</div>')+'</div><h3>이용 환경</h3><div class="feedback-bars">'+(fb.platforms.map(x=>'<div class="feedback-bar"><span>'+esc(labels[x.client_kind]||x.client_kind)+'</span><div class="track"><div class="fill" style="width:'+Number(x.count)/platformMax*100+'%"></div></div><strong>'+number(x.count)+'</strong></div>').join('')||'<div class="empty">아직 이용 환경 데이터가 없습니다.</div>')+'</div><h3>최근 의견</h3><div class="feedback-list">'+(fb.recent.map(x=>'<article class="feedback-item"><small>'+esc(x.feedback_date)+' · '+esc(labels[x.sentiment]||x.sentiment)+' · '+esc(labels[x.client_kind]||x.client_kind)+(x.surface==='demo'?' · 데모':'')+'</small><b>'+esc(labels[x.reason]||'상세 사유 없음')+'</b>'+(x.comment?'<p>'+esc(x.comment)+'</p>':'')+'</article>').join('')||'<div class="empty">아직 제출된 피드백이 없습니다.</div>')+'</div></section>';
 document.querySelector('#app').className='';document.querySelector('#app').innerHTML='<div class="cards"><div class="card"><small>랜딩 세션</small><b>'+number(views)+'</b><em>선택 기간</em></div><div class="card"><small>정식 서비스</small><b>'+number(apps)+'</b><em>데모 '+number(demos)+'회</em></div><div class="card"><small>여행방 생성</small><b>'+number(rooms)+'</b><em>서비스 대비 '+rate(rooms,apps)+'%</em></div><div class="card"><small>최종 경로</small><b>'+number(finals)+'</b><em>생성 대비 '+rate(finals,rooms)+'%</em></div></div><section><h2>정식 서비스 전환 흐름</h2><div class="funnel">'+funnel.map(k=>'<div class="row"><span>'+esc(data.labels[k]||k)+'</span><div class="track"><div class="fill" style="width:'+(counts[k]||0)/max*100+'%"></div></div><strong>'+number(counts[k])+'</strong></div>').join('')+'</div></section>'+feedbackSection+'<section><h2>날짜별 추이</h2><div class="daily">'+(Object.entries(days).slice(-31).map(([day,c])=>'<div class="daily-row"><span>'+day.slice(5)+'</span><div><i style="width:'+(c.app_view||0)/dayMax*100+'%"></i></div><div><i class="demo" style="width:'+(c.demo_view||0)/dayMax*100+'%"></i></div></div>').join('')||'<div class="empty">아직 날짜별 데이터가 없습니다.</div>')+'</div></section><section><h2>광고 캠페인별 결과</h2><div class="campaigns">'+(Object.keys(grouped).length?Object.entries(grouped).map(([name,c])=>'<div class="campaign"><b>'+esc(name)+'</b><strong>랜딩 '+number(c.landing_view)+' · 서비스 '+number(c.app_view)+'</strong><span>생성 '+number(c.room_created)+' · 최종 '+number(c.final_route_confirmed)+'</span></div>').join(''):'<div class="empty">아직 UTM 유입이 없습니다.</div>')+'</div></section><p class="privacy">피드백에는 만족 여부, 선택 사유, 사용자가 직접 적은 의견, 웹·앱 구분만 저장합니다. 의견란에 개인정보를 적지 않도록 안내합니다.</p>';
 document.querySelector('#updated').textContent=new Date().toLocaleString('ko-KR')+' 확인';
}).catch(()=>{document.querySelector('#app').innerHTML='<p class="error">통계를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.</p>'});
</script></body></html>`
