/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";
import { deleteExpiredRooms, handleRoomApi } from "./rooms";
import { cachedPlaceSearch, selectBestPlaceMatch } from "./recommendations";
import { publicDataStatus, syncPublicData } from "./public-data";
import { handleAnalyticsDashboard } from "./analytics-dashboard";
import { consumeRateLimit } from "./operations";

interface Env {
  DB: D1Database;
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
  NAVER_MAPS_CLIENT_ID?: string;
  NAVER_MAPS_CLIENT_SECRET?: string;
  NAVER_SEARCH_CLIENT_ID?: string;
  NAVER_SEARCH_CLIENT_SECRET?: string;
  PUBLIC_DATA_SERVICE_KEY?: string;
  PUBLIC_DATA_SYNC_TOKEN?: string;
  ANALYTICS_VIEW_TOKEN?: string;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

function secured(response: Response, cacheControl?: string) {
  const headers = new Headers(response.headers);
  headers.set('X-Content-Type-Options', 'nosniff');
  headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');
  headers.set('Permissions-Policy', 'camera=(), microphone=(), geolocation=()');
  headers.set('X-Frame-Options', 'DENY');
  headers.set('Content-Security-Policy', "frame-ancestors 'none'; base-uri 'self'; object-src 'none'");
  if (cacheControl) headers.set('Cache-Control', cacheControl);
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}

async function rateLimitResponse(db: D1Database, scope: string, limit: number, windowSeconds: number) {
  const result = await consumeRateLimit(db, scope, limit, windowSeconds);
  return result.allowed ? null : Response.json({ error: '요청이 많습니다. 잠시 후 다시 시도해 주세요.' }, {
    status: 429, headers: { 'Retry-After': String(result.retryAfter), 'Cache-Control': 'no-store' },
  });
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    const analyticsResponse = await handleAnalyticsDashboard(request, env, url);
    if (analyticsResponse) return analyticsResponse;

    if (url.pathname === "/api/events" && request.method === "POST") {
      const limited = await rateLimitResponse(env.DB, 'events:global', 5000, 3600);
      if (limited) return secured(limited);
      const allowed = new Set([
        "landing_view", "app_view", "demo_view", "landing_interest_yes", "landing_interest_not_yet", "landing_app_click", "landing_demo_click",
        "room_created", "recommendations_viewed", "final_route_confirmed", "schedule_edit", "schedule_copy",
        "demo_room_created", "demo_recommendations_viewed", "demo_final_route_confirmed",
        "feedback_helpful", "feedback_not_helpful", "beta_interest", "interview_interest",
      ]);
      try {
        const body = await request.json<{ name?: string; source?: string; medium?: string; campaign?: string; firstInSession?: boolean }>();
        if (!body.name || !allowed.has(body.name)) return Response.json({ error: "허용되지 않은 이벤트입니다." }, { status: 400 });
        const clean = (value?: string) => String(value ?? "").replace(/[^\p{L}\p{N}_.-]/gu, "").slice(0, 80);
        const day = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Seoul', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
        const now = Math.floor(Date.now() / 1000);
        await env.DB.prepare(`INSERT INTO anonymous_event_counts
          (event_date,event_name,campaign_source,campaign_medium,campaign_name,event_count,session_count,updated_at)
          VALUES (?1,?2,?3,?4,?5,1,?6,?7)
          ON CONFLICT(event_date,event_name,campaign_source,campaign_medium,campaign_name)
          DO UPDATE SET event_count=event_count+1,session_count=session_count+excluded.session_count,updated_at=excluded.updated_at`)
          .bind(day, body.name, clean(body.source), clean(body.medium), clean(body.campaign), body.firstInSession ? 1 : 0, now).run();
        return Response.json({ ok: true }, { status: 202, headers: { "Cache-Control": "no-store" } });
      } catch {
        return Response.json({ error: "이벤트 형식을 확인해 주세요." }, { status: 400 });
      }
    }

    if (url.pathname.startsWith('/api/rooms')) {
      if (url.pathname === '/api/rooms' && request.method === 'POST') {
        const limited = await rateLimitResponse(env.DB, 'rooms:create:global', 1000, 3600);
        if (limited) return secured(limited);
      }
      const joinMatch = request.method === 'POST' && url.pathname.match(/^\/api\/rooms\/([a-z0-9]+)\/members$/);
      if (joinMatch) {
        const limited = await rateLimitResponse(env.DB, `rooms:join:${joinMatch[1]}`, 30, 600);
        if (limited) return secured(limited);
      }
      const roomResponse = await handleRoomApi(request, env.DB, url, {
        clientId: env.NAVER_SEARCH_CLIENT_ID,
        clientSecret: env.NAVER_SEARCH_CLIENT_SECRET,
      });
      if (roomResponse) return secured(roomResponse);
    }

    if (url.pathname === "/api/naver/config") {
      return secured(Response.json({
        enabled: Boolean(env.NAVER_MAPS_CLIENT_ID),
        clientId: env.NAVER_MAPS_CLIENT_ID ?? null,
      }, { headers: { "Cache-Control": "public, max-age=3600" } }));
    }

    if (url.pathname === "/api/naver/route" && request.method === "GET") {
      if (!env.NAVER_MAPS_CLIENT_ID || !env.NAVER_MAPS_CLIENT_SECRET) {
        return secured(Response.json({ error: "네이버 경로 API가 설정되지 않았습니다." }, { status: 503 }));
      }
      const rawPoints = url.searchParams.get("points") ?? "";
      const points = rawPoints.split("|").map((value) => value.split(",").map(Number));
      const valid = points.length >= 2 && points.length <= 6 && points.every(([lng, lat]) =>
        Number.isFinite(lng) && Number.isFinite(lat) && lng >= 128.7 && lng <= 129.4 && lat >= 34.8 && lat <= 35.5);
      if (!valid) return secured(Response.json({ error: "경로 좌표를 확인해 주세요." }, { status: 400 }));

      const normalized = points.map(([lng, lat]) => `${lng.toFixed(6)},${lat.toFixed(6)}`).join("|");
      const cacheKey = `naver:directions:v1:${normalized}`;
      const now = Math.floor(Date.now() / 1000);
      const cached = await env.DB.prepare("SELECT response_json FROM place_search_cache WHERE cache_key=?1 AND expires_at>=?2")
        .bind(cacheKey, now).first<{ response_json: string }>();
      if (cached?.response_json) {
        try { return secured(Response.json(JSON.parse(cached.response_json), { headers: { "Cache-Control": "public, max-age=3600" } })); } catch { /* refresh */ }
      }
      const limited = await rateLimitResponse(env.DB, "naver-route:global", 1000, 3600);
      if (limited) return secured(limited);

      const endpoint = new URL("https://maps.apigw.ntruss.com/map-direction/v1/driving");
      endpoint.searchParams.set("start", points[0].join(","));
      endpoint.searchParams.set("goal", points.at(-1)!.join(","));
      if (points.length > 2) endpoint.searchParams.set("waypoints", points.slice(1, -1).map((point) => point.join(",")).join("|"));
      endpoint.searchParams.set("option", "traavoidcaronly");
      const response = await fetch(endpoint, { headers: {
        "x-ncp-apigw-api-key-id": env.NAVER_MAPS_CLIENT_ID,
        "x-ncp-apigw-api-key": env.NAVER_MAPS_CLIENT_SECRET,
      } });
      if (!response.ok) {
        console.error("naver-directions-error", { status: response.status, detail: (await response.text()).slice(0, 300) });
        return secured(Response.json({ error: "실제 도로 경로를 불러오지 못했습니다." }, { status: 502 }));
      }
      const data = await response.json<any>();
      const route = data.route?.traavoidcaronly?.[0] ?? data.route?.traoptimal?.[0];
      if (!route?.path?.length) return secured(Response.json({ error: "사용 가능한 도로 경로가 없습니다." }, { status: 404 }));
      const result = {
        path: route.path.map((point: number[]) => [Number(point[0]), Number(point[1])]),
        distanceMeters: Number(route.summary?.distance ?? 0),
        durationMinutes: Math.max(1, Math.round(Number(route.summary?.duration ?? 0) / 60000)),
        basis: "NAVER_DIRECTIONS_ROAD",
      };
      await env.DB.prepare(`INSERT INTO place_search_cache (cache_key,response_json,fetched_at,expires_at) VALUES (?1,?2,?3,?4)
        ON CONFLICT(cache_key) DO UPDATE SET response_json=excluded.response_json,fetched_at=excluded.fetched_at,expires_at=excluded.expires_at`)
        .bind(cacheKey, JSON.stringify(result), now, now + 24 * 60 * 60).run();
      return secured(Response.json(result, { headers: { "Cache-Control": "public, max-age=3600" } }));
    }

    if (url.pathname === "/api/public-data/status" && request.method === "GET") {
      const providers = await publicDataStatus(env.DB);
      return secured(Response.json({ enabled: Boolean(env.PUBLIC_DATA_SERVICE_KEY), providers: providers.map((item: any) => ({
        provider: item.provider, status: item.status, lastCompletedAt: item.last_completed_at, itemCount: item.item_count,
      })) }, {
        headers: { "Cache-Control": "public, max-age=300" },
      }));
    }

    if (url.pathname === "/api/health" && request.method === "GET") {
      const providers = await publicDataStatus(env.DB) as any[];
      const unavailable = providers.filter((item) => item.status === 'failed' && Number(item.item_count) === 0).map((item) => item.provider);
      const stale = providers.filter((item) => item.status === 'stale').map((item) => item.provider);
      const empty = providers.filter((item) => item.status === 'empty').map((item) => item.provider);
      const dataStatus = unavailable.length || stale.length || empty.length ? 'degraded' : 'ok';
      return secured(Response.json({ status: 'ok', dataStatus, unavailable, stale, empty }, {
        status: 200, headers: { 'Cache-Control': 'no-store' },
      }));
    }

    if (url.pathname === "/api/data-health" && request.method === "GET") {
      const providers = await publicDataStatus(env.DB) as any[];
      const now = Math.floor(Date.now() / 1000);
      const unavailable = providers.filter((item) => item.status === 'failed' && Number(item.item_count) === 0).map((item) => item.provider);
      const stale = providers.filter((item) => item.status === 'stale').map((item) => item.provider);
      const empty = providers.filter((item) => item.status === 'empty').map((item) => item.provider);
      const overdue = providers.filter((item) => item.provider !== 'TOUR_DETAIL' && (!item.last_completed_at || now - Number(item.last_completed_at) > 72 * 60 * 60)).map((item) => item.provider);
      const unavailableSet = [...new Set([...unavailable, ...overdue])];
      const status = unavailableSet.length ? 'unavailable' : stale.length || empty.length ? 'degraded' : 'ok';
      return secured(Response.json({ status, unavailable: unavailableSet, stale, empty, checkedAt: now }, {
        status: unavailableSet.length ? 503 : 200, headers: { 'Cache-Control': 'no-store' },
      }));
    }

    if (url.pathname === "/api/public-data/sync") {
      if (request.method !== "POST") return new Response("Method Not Allowed", { status: 405 });
      const token = request.headers.get("X-Sync-Token");
      if (!env.PUBLIC_DATA_SYNC_TOKEN || token !== env.PUBLIC_DATA_SYNC_TOKEN) {
        return secured(Response.json({ error: "Unauthorized" }, { status: 401 }));
      }
      const limited = await rateLimitResponse(env.DB, 'public-data:sync', 12, 3600);
      if (limited) return secured(limited);
      const providers = url.searchParams.get("providers")?.split(",").map((value) => value.trim()).filter(Boolean);
      const result = await syncPublicData({ DB: env.DB, PUBLIC_DATA_SERVICE_KEY: env.PUBLIC_DATA_SERVICE_KEY }, providers);
      return secured(Response.json(result, { headers: { "Cache-Control": "no-store" } }));
    }

    if (url.pathname === "/api/naver/local") {
      if (request.method !== "GET") return new Response("Method Not Allowed", { status: 405 });
      const query = url.searchParams.get("query")?.trim();
      const expectedTitle = url.searchParams.get("title")?.trim();
      const latitude = Number(url.searchParams.get("lat"));
      const longitude = Number(url.searchParams.get("lng"));
      if (!query || query.length > 80) return Response.json({ error: "검색어를 확인해 주세요." }, { status: 400 });
      if (!env.NAVER_SEARCH_CLIENT_ID || !env.NAVER_SEARCH_CLIENT_SECRET) {
        return Response.json({ error: "네이버 지역 검색이 아직 설정되지 않았습니다." }, { status: 503 });
      }
      const limited = await rateLimitResponse(env.DB, 'naver-local:global', 1000, 3600);
      if (limited) return secured(limited);
      try {
        const items = await cachedPlaceSearch(query, {
          clientId: env.NAVER_SEARCH_CLIENT_ID,
          clientSecret: env.NAVER_SEARCH_CLIENT_SECRET,
        }, env.DB);
        const selectedItems = expectedTitle
          ? (() => {
              const best = selectBestPlaceMatch(items, { title: expectedTitle, latitude, longitude });
              return best ? [best] : [];
            })()
          : items;
        return Response.json({ items: selectedItems.map((item) => ({
          title: item.title,
          category: item.category,
          roadAddress: item.roadAddress,
          mapx: Math.round(item.longitude * 10_000_000),
          mapy: Math.round(item.latitude * 10_000_000),
          link: `https://map.naver.com/p/search/${encodeURIComponent(item.title)}`,
        })) }, { headers: { "Cache-Control": "public, max-age=900, stale-while-revalidate=86400" } });
      } catch (reason) {
        console.error("naver-local-api-failed", reason);
        return Response.json({ error: "네이버 장소 정보를 불러오지 못했습니다." }, { status: 502 });
      }
    }

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
    }

    // Delegate everything else to vinext, forwarding ctx so that
    // ctx.waitUntil() is available to background cache writes and
    // other deferred work via getRequestExecutionContext().
    const response = await handler.fetch(request, env, ctx);
    const cacheControl = url.pathname === '/' && request.headers.get('RSC') !== '1'
      ? 'public, max-age=0, s-maxage=300, stale-while-revalidate=86400'
      : undefined;
    return secured(response, cacheControl);
  },
  async scheduled(_controller: ScheduledController, env: Env, ctx: ExecutionContext) {
    ctx.waitUntil(Promise.all([
      deleteExpiredRooms(env.DB),
      env.DB.prepare("DELETE FROM anonymous_event_counts WHERE event_date < date('now','+9 hours','-180 days')").run(),
      env.DB.prepare("DELETE FROM request_rate_limits WHERE expires_at < strftime('%s','now')").run(),
      syncPublicData({ DB: env.DB, PUBLIC_DATA_SERVICE_KEY: env.PUBLIC_DATA_SERVICE_KEY }),
    ]));
  },
};
