/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
  NAVER_MAPS_CLIENT_ID?: string;
  NAVER_MAPS_CLIENT_SECRET?: string;
  NAVER_SEARCH_CLIENT_ID?: string;
  NAVER_SEARCH_CLIENT_SECRET?: string;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/api/naver/config") {
      return Response.json({
        enabled: Boolean(env.NAVER_MAPS_CLIENT_ID),
        clientId: env.NAVER_MAPS_CLIENT_ID ?? null,
      }, { headers: { "Cache-Control": "public, max-age=3600" } });
    }

    if (url.pathname === "/api/naver/local") {
      if (request.method !== "GET") return new Response("Method Not Allowed", { status: 405 });
      const query = url.searchParams.get("query")?.trim();
      if (!query || query.length > 80) return Response.json({ error: "검색어를 확인해 주세요." }, { status: 400 });
      if (!env.NAVER_SEARCH_CLIENT_ID || !env.NAVER_SEARCH_CLIENT_SECRET) {
        return Response.json({ error: "네이버 지역 검색이 아직 설정되지 않았습니다." }, { status: 503 });
      }
      const endpoint = new URL("https://openapi.naver.com/v1/search/local.json");
      endpoint.searchParams.set("query", query);
      endpoint.searchParams.set("display", "5");
      endpoint.searchParams.set("sort", "random");
      const response = await fetch(endpoint, {
        headers: {
          "X-Naver-Client-Id": env.NAVER_SEARCH_CLIENT_ID,
          "X-Naver-Client-Secret": env.NAVER_SEARCH_CLIENT_SECRET,
        },
      });
      if (!response.ok) return Response.json({ error: "네이버 장소 정보를 불러오지 못했습니다." }, { status: 502 });
      const data = await response.json() as { items?: Array<Record<string, unknown>> };
      const stripTags = (value: unknown) => String(value ?? "").replace(/<[^>]*>/g, "");
      return Response.json({
        items: (data.items ?? []).map((item) => ({
          title: stripTags(item.title),
          category: item.category,
          address: item.address,
          roadAddress: item.roadAddress,
          mapx: item.mapx,
          mapy: item.mapy,
          link: item.link,
        })),
      }, { headers: { "Cache-Control": "public, max-age=900" } });
    }

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
    }

    // Delegate everything else to vinext, forwarding ctx so that
    // ctx.waitUntil() is available to background cache writes and
    // other deferred work via getRequestExecutionContext().
    return handler.fetch(request, env, ctx);
  },
};
